[package]
name = "h3-quinn"
version = "0.0.0"
authors = ["Jean-Christophe BEGUE <jc.begue@pm.me>"]
edition = "2018"

[dependencies]
h3 = { path = "../h3" }
bytes = "1"
quinn = { version = "0.8.0", default-features = false }
quinn-proto = { version = "0.8.0", default-features = false }
futures = "0.3"

[dev-dependencies]
http = "0.2"
tokio = "1"
